/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 *        
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.politaktiv.map.infrastructure.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Background service. Represents a row in the &quot;politaktivmap_Background&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.politaktiv.map.infrastructure.model.impl.BackgroundModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.politaktiv.map.infrastructure.model.impl.BackgroundImpl}.
 * </p>
 *
 * @author eichi
 * @see Background
 * @see org.politaktiv.map.infrastructure.model.impl.BackgroundImpl
 * @see org.politaktiv.map.infrastructure.model.impl.BackgroundModelImpl
 * @generated
 */
public interface BackgroundModel extends BaseModel<Background> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a background model instance should use the {@link Background} interface instead.
	 */

	/**
	 * Returns the primary key of this background.
	 *
	 * @return the primary key of this background
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this background.
	 *
	 * @param primaryKey the primary key of this background
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the background ID of this background.
	 *
	 * @return the background ID of this background
	 */
	public long getBackgroundId();

	/**
	 * Sets the background ID of this background.
	 *
	 * @param backgroundId the background ID of this background
	 */
	public void setBackgroundId(long backgroundId);

	/**
	 * Returns the company ID of this background.
	 *
	 * @return the company ID of this background
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this background.
	 *
	 * @param companyId the company ID of this background
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this background.
	 *
	 * @return the group ID of this background
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this background.
	 *
	 * @param groupId the group ID of this background
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this background.
	 *
	 * @return the user ID of this background
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this background.
	 *
	 * @param userId the user ID of this background
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this background.
	 *
	 * @return the user uuid of this background
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this background.
	 *
	 * @param userUuid the user uuid of this background
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the name of this background.
	 *
	 * @return the name of this background
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this background.
	 *
	 * @param name the name of this background
	 */
	public void setName(String name);

	/**
	 * Returns the file entry uuid of this background.
	 *
	 * @return the file entry uuid of this background
	 */
	@AutoEscape
	public String getFileEntryUuid();

	/**
	 * Sets the file entry uuid of this background.
	 *
	 * @param fileEntryUuid the file entry uuid of this background
	 */
	public void setFileEntryUuid(String fileEntryUuid);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Background background);

	public int hashCode();

	public CacheModel<Background> toCacheModel();

	public Background toEscapedModel();

	public String toString();

	public String toXmlString();
}