/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 *        
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.politaktiv.map.infrastructure.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DbMarker service. Represents a row in the &quot;politaktivmap_DbMarker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.politaktiv.map.infrastructure.model.impl.DbMarkerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.politaktiv.map.infrastructure.model.impl.DbMarkerImpl}.
 * </p>
 *
 * @author eichi
 * @see DbMarker
 * @see org.politaktiv.map.infrastructure.model.impl.DbMarkerImpl
 * @see org.politaktiv.map.infrastructure.model.impl.DbMarkerModelImpl
 * @generated
 */
public interface DbMarkerModel extends BaseModel<DbMarker> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a db marker model instance should use the {@link DbMarker} interface instead.
	 */

	/**
	 * Returns the primary key of this db marker.
	 *
	 * @return the primary key of this db marker
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this db marker.
	 *
	 * @param primaryKey the primary key of this db marker
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the marker ID of this db marker.
	 *
	 * @return the marker ID of this db marker
	 */
	public long getMarkerId();

	/**
	 * Sets the marker ID of this db marker.
	 *
	 * @param markerId the marker ID of this db marker
	 */
	public void setMarkerId(long markerId);

	/**
	 * Returns the marker image name of this db marker.
	 *
	 * @return the marker image name of this db marker
	 */
	@AutoEscape
	public String getMarkerImageName();

	/**
	 * Sets the marker image name of this db marker.
	 *
	 * @param markerImageName the marker image name of this db marker
	 */
	public void setMarkerImageName(String markerImageName);

	/**
	 * Returns the point ID of this db marker.
	 *
	 * @return the point ID of this db marker
	 */
	public long getPointId();

	/**
	 * Sets the point ID of this db marker.
	 *
	 * @param pointId the point ID of this db marker
	 */
	public void setPointId(long pointId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DbMarker dbMarker);

	public int hashCode();

	public CacheModel<DbMarker> toCacheModel();

	public DbMarker toEscapedModel();

	public String toString();

	public String toXmlString();
}