/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 *        
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.politaktiv.map.infrastructure.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DbMapObject service. Represents a row in the &quot;politaktivmap_DbMapObject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.politaktiv.map.infrastructure.model.impl.DbMapObjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.politaktiv.map.infrastructure.model.impl.DbMapObjectImpl}.
 * </p>
 *
 * @author eichi
 * @see DbMapObject
 * @see org.politaktiv.map.infrastructure.model.impl.DbMapObjectImpl
 * @see org.politaktiv.map.infrastructure.model.impl.DbMapObjectModelImpl
 * @generated
 */
public interface DbMapObjectModel extends BaseModel<DbMapObject> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a db map object model instance should use the {@link DbMapObject} interface instead.
	 */

	/**
	 * Returns the primary key of this db map object.
	 *
	 * @return the primary key of this db map object
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this db map object.
	 *
	 * @param primaryKey the primary key of this db map object
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the map object ID of this db map object.
	 *
	 * @return the map object ID of this db map object
	 */
	public long getMapObjectId();

	/**
	 * Sets the map object ID of this db map object.
	 *
	 * @param mapObjectId the map object ID of this db map object
	 */
	public void setMapObjectId(long mapObjectId);

	/**
	 * Returns the company ID of this db map object.
	 *
	 * @return the company ID of this db map object
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this db map object.
	 *
	 * @param companyId the company ID of this db map object
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this db map object.
	 *
	 * @return the group ID of this db map object
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this db map object.
	 *
	 * @param groupId the group ID of this db map object
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this db map object.
	 *
	 * @return the user ID of this db map object
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this db map object.
	 *
	 * @param userId the user ID of this db map object
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this db map object.
	 *
	 * @return the user uuid of this db map object
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this db map object.
	 *
	 * @param userUuid the user uuid of this db map object
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the name of this db map object.
	 *
	 * @return the name of this db map object
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this db map object.
	 *
	 * @param name the name of this db map object
	 */
	public void setName(String name);

	/**
	 * Returns the description of this db map object.
	 *
	 * @return the description of this db map object
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this db map object.
	 *
	 * @param description the description of this db map object
	 */
	public void setDescription(String description);

	/**
	 * Returns the reference url of this db map object.
	 *
	 * @return the reference url of this db map object
	 */
	@AutoEscape
	public String getReferenceUrl();

	/**
	 * Sets the reference url of this db map object.
	 *
	 * @param referenceUrl the reference url of this db map object
	 */
	public void setReferenceUrl(String referenceUrl);

	/**
	 * Returns the occupancy of this db map object.
	 *
	 * @return the occupancy of this db map object
	 */
	public long getOccupancy();

	/**
	 * Sets the occupancy of this db map object.
	 *
	 * @param occupancy the occupancy of this db map object
	 */
	public void setOccupancy(long occupancy);

	/**
	 * Returns the map ID of this db map object.
	 *
	 * @return the map ID of this db map object
	 */
	public long getMapId();

	/**
	 * Sets the map ID of this db map object.
	 *
	 * @param mapId the map ID of this db map object
	 */
	public void setMapId(long mapId);

	/**
	 * Returns the type of this db map object.
	 *
	 * @return the type of this db map object
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this db map object.
	 *
	 * @param type the type of this db map object
	 */
	public void setType(String type);

	/**
	 * Returns the graphic object ID of this db map object.
	 *
	 * @return the graphic object ID of this db map object
	 */
	public long getGraphicObjectId();

	/**
	 * Sets the graphic object ID of this db map object.
	 *
	 * @param graphicObjectId the graphic object ID of this db map object
	 */
	public void setGraphicObjectId(long graphicObjectId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DbMapObject dbMapObject);

	public int hashCode();

	public CacheModel<DbMapObject> toCacheModel();

	public DbMapObject toEscapedModel();

	public String toString();

	public String toXmlString();
}