/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 *        
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.politaktiv.map.infrastructure.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.politaktiv.map.infrastructure.model.DbPoint;
import org.politaktiv.map.infrastructure.service.DbPointLocalServiceUtil;

/**
 * The extended model base implementation for the DbPoint service. Represents a row in the &quot;politaktivmap_DbPoint&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DbPointImpl}.
 * </p>
 *
 * @author eichi
 * @see DbPointImpl
 * @see org.politaktiv.map.infrastructure.model.DbPoint
 * @generated
 */
public abstract class DbPointBaseImpl extends DbPointModelImpl
	implements DbPoint {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a db point model instance should use the {@link DbPoint} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			DbPointLocalServiceUtil.addDbPoint(this);
		}
		else {
			DbPointLocalServiceUtil.updateDbPoint(this);
		}
	}
}